### ISSUE TITLE
Idea Tracker

### ISSUE THREAD

**Issue by exterkamp** [exterkamp/lighthouse-cli-viewer#1]
- [ ] use chalk, `FORCE_COLOR` for gh action
- [ ] `expand`
  - [ ] `expand` for category, to show a high level of audits in their clumps
  - [ ] `expand` specific audits, or `expand-full` on category to show all audits+details
- [ ] runtime settings
- [ ] just gauges?
